language: go

go:
  - 1.8

services:
  - rabbitmq

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -v gopkg.in/mgo.v2
  - go get -v github.com/gin-gonic/gin
script:
  - ./pre-commit
  - go test -cpu=1,2 -v -tags integration ./...