language: go

go:
  - 1.8

services:
  - mongodb
env:
 - PORT=8080

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -v gopkg.in/mgo.v2
  - go get -v github.com/gin-gonic/gin
  - go get -v github.com/kardianos/govendor
script:
  # - ./pre-commit
  - govendor list
  - go test -cpu=1,2 -v -tags integration ./...

os:
  - linux

addons:
  hosts:
    - travis.dev